export const datas = [
  {
    name: "Blue RoundNeck",
    amount: "45.00",
    discount: "5.00",
    rating: "4.2",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "EcoElegance Gown",
    amount: "50.00",
    discount: "10.00",
    rating: "4.5",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Chic Casual Tee",
    amount: "20.00",
    discount: "2.00",
    rating: "4.0",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Summer Breeze Dress",
    amount: "75.00",
    discount: "15.00",
    rating: "4.7",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Classic Polo",
    amount: "30.00",
    discount: "3.00",
    rating: "4.1",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Winter Wool Coat",
    amount: "120.00",
    discount: "20.00",
    rating: "4.8",
    percentage: "16%",
    image: "/frame2.png",
  },
  {
    name: "Spring Blossom Skirt",
    amount: "40.00",
    discount: "5.00",
    rating: "4.3",
    percentage: "12%",
    image: "/frame1.png",
  },
  {
    name: "Urban Denim Jacket",
    amount: "60.00",
    discount: "12.00",
    rating: "4.6",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Elegant Evening Gown",
    amount: "150.00",
    discount: "30.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Cozy Knit Sweater",
    amount: "55.00",
    discount: "5.00",
    rating: "4.4",
    percentage: "9%",
    image: "/frame2.png",
  },
  {
    name: "Sporty Tracksuit",
    amount: "85.00",
    discount: "17.00",
    rating: "4.7",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Retro Graphic Tee",
    amount: "25.00",
    discount: "2.50",
    rating: "4.0",
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Modern Office Blazer",
    amount: "70.00",
    discount: "14.00",
    rating: "4.6",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Flowy Maxi Dress",
    amount: "65.00",
    discount: "13.00",
    rating: "4.5",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Stylish Trench Coat",
    amount: "110.00",
    discount: "22.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Basic White Shirt",
    amount: "15.00",
    discount: "1.50",
    rating: "4.1",
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Vintage Leather Jacket",
    amount: "200.00",
    discount: "40.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Silk Blouse",
    amount: "90.00",
    discount: "9.00",
    rating: "4.5",
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Casual Denim Shorts",
    amount: "35.00",
    discount: "7.00",
    rating: "4.3",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Floral Sundress",
    amount: "55.00",
    discount: "11.00",
    rating: "4.4",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Comfy Lounge Pants",
    amount: "40.00",
    discount: "8.00",
    rating: "4.2",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Formal Business Suit",
    amount: "180.00",
    discount: "36.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Party Sequin Dress",
    amount: "130.00",
    discount: "26.00",
    rating: "4.7",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Warm Puffer Jacket",
    amount: "95.00",
    discount: "19.00",
    rating: "4.6",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Trendy Crop Top",
    amount: "20.00",
    discount: "2.00",
    rating: "4.1",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Lace Dress",
    amount: "140.00",
    discount: "28.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Soft Cashmere Sweater",
    amount: "120.00",
    discount: "24.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Athletic Joggers",
    amount: "50.00",
    discount: "5.00",
    rating: "4.3",
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Bold Patterned Shirt",
    amount: "30.00",
    discount: "3.00",
    rating: "4.2",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Classic Little Black Dress",
    amount: "100.00",
    discount: "20.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Beachside Swimwear",
    amount: "40.00",
    discount: "8.00",
    rating: "4.4",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Retro Bell Bottoms",
    amount: "60.00",
    discount: "12.00",
    rating: "4.5",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Stylish Fedora Hat",
    amount: "25.00",
    discount: "2.50",
    rating: "4.1",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Pearl Necklace",
    amount: "200.00",
    discount: "40.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Fashionable Sunglasses",
    amount: "75.00",
    discount: "15.00",
    rating: "4.6",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Chic Handbag",
    amount: "150.00",
    discount: "30.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Casual Slip-on Shoes",
    amount: "55.00",
    discount: "11.00",
    rating: "4.4",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Designer Watch",
    amount: "300.00",
    discount: "60.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Modern Backpack",
    amount: "80.00",
    discount: "16.00",
    rating: "4.5",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Evening Shoes",
    amount: "120.00",
    discount: "24.00",
    rating: "4.7",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Trendy Baseball Cap",
    amount: "20.00",
    discount: "2.00",
    rating: "4.0",
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Luxury Silk Scarf",
    amount: "100.00",
    discount: "20.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Classic Leather Belt",
    amount: "35.00",
    discount: "7.00",
    rating: "4.3",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Fashionable Boots",
    amount: "150.00",
    discount: "30.00",
    rating: "4.9",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Stylish Beanie",
    amount: "25.00",
    discount: "5.00",
    rating: "4.1",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Brooch",
    amount: "50.00",
    discount: "10.00",
    rating: "4.4",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Retro Aviator Jacket",
    amount: "220.00",
    discount: "44.00",
    rating: "4.8",
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Casual Slip Dress",
    amount: "60.00",
    discount: "12.00",
    rating: "4.5",
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Classic Cardigan",
    amount: "45.00",
    discount: "9.00",
    rating: "4.2",
    percentage: "20%",
    image: "/frame1.png",
  },
];
