export const datas = [
  {
    name: "Blue RoundNeck",
    amount: 45.0,
    discount: 5.0,
    rating: 4.2,
    percentage: "10%",
    image: "/frame7.png",
  },
  {
    name: "EcoElegance Gown",
    amount: 50.0,
    discount: 10.0,
    rating: 4.5,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Chic Casual Tee",
    amount: 20.0,
    discount: 2.0,
    rating: 4.0,
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Summer Breeze Dress",
    amount: 75.0,
    discount: 15.0,
    rating: 4.7,
    percentage: "20%",
    image: "/frame7.png",
  },
  {
    name: "Classic Polo",
    amount: 30.0,
    discount: 3.0,
    rating: 4.1,
    percentage: "10%",
    image: "/frame2.png",
  },
  {
    name: "Winter Wool Coat",
    amount: 120.0,
    discount: 20.0,
    rating: 4.8,
    percentage: "16%",
    image: "/frame7.png",
  },
  {
    name: "Spring Blossom Skirt",
    amount: 40.0,
    discount: 5.0,
    rating: 4.3,
    percentage: "12%",
    image: "/frame2.png",
  },
  {
    name: "Urban Denim Jacket",
    amount: 60.0,
    discount: 12.0,
    rating: 4.6,
    percentage: "20%",
    image: "/frame7.png",
  },
  {
    name: "Elegant Evening Gown",
    amount: 150.0,
    discount: 30.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Cozy Knit Sweater",
    amount: 55.0,
    discount: 5.0,
    rating: 4.4,
    percentage: "9%",
    image: "/frame7.png",
  },
  {
    name: "Sporty Tracksuit",
    amount: 85.0,
    discount: 17.0,
    rating: 4.7,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Retro Graphic Tee",
    amount: 25.0,
    discount: 2.5,
    rating: 4.0,
    percentage: "10%",
    image: "/frame3.png",
  },
  {
    name: "Modern Office Blazer",
    amount: 70.0,
    discount: 14.0,
    rating: 4.6,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Flowy Maxi Dress",
    amount: 65.0,
    discount: 13.0,
    rating: 4.5,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Stylish Trench Coat",
    amount: 110.0,
    discount: 22.0,
    rating: 4.8,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Basic White Shirt",
    amount: 15.0,
    discount: 1.5,
    rating: 4.1,
    percentage: "10%",
    image: "/frame3.png",
  },
  {
    name: "Vintage Leather Jacket",
    amount: 200.0,
    discount: 40.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Silk Blouse",
    amount: 90.0,
    discount: 9.0,
    rating: 4.5,
    percentage: "10%",
    image: "/frame3.png",
  },
  {
    name: "Casual Denim Shorts",
    amount: 35.0,
    discount: 7.0,
    rating: 4.3,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Floral Sundress",
    amount: 55.0,
    discount: 11.0,
    rating: 4.4,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Comfy Lounge Pants",
    amount: 40.0,
    discount: 8.0,
    rating: 4.2,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Formal Business Suit",
    amount: 180.0,
    discount: 36.0,
    rating: 4.8,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Party Sequin Dress",
    amount: 130.0,
    discount: 26.0,
    rating: 4.7,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Warm Puffer Jacket",
    amount: 95.0,
    discount: 19.0,
    rating: 4.6,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Trendy Crop Top",
    amount: 20.0,
    discount: 2.0,
    rating: 4.1,
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Lace Dress",
    amount: 140.0,
    discount: 28.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame7.png",
  },
  {
    name: "Soft Cashmere Sweater",
    amount: 120.0,
    discount: 24.0,
    rating: 4.8,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Athletic Joggers",
    amount: 50.0,
    discount: 5.0,
    rating: 4.3,
    percentage: "10%",
    image: "/frame7.png",
  },
  {
    name: "Bold Patterned Shirt",
    amount: 30.0,
    discount: 3.0,
    rating: 4.2,
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Classic Little Black Dress",
    amount: 100.0,
    discount: 20.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame7.png",
  },
  {
    name: "Beachside Swimwear",
    amount: 40.0,
    discount: 8.0,
    rating: 4.4,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Retro Bell Bottoms",
    amount: 60.0,
    discount: 12.0,
    rating: 4.5,
    percentage: "20%",
    image: "/frame7.png",
  },
  {
    name: "Stylish Fedora Hat",
    amount: 25.0,
    discount: 2.5,
    rating: 4.1,
    percentage: "10%",
    image: "/frame1.png",
  },
  {
    name: "Elegant Pearl Necklace",
    amount: 200.0,
    discount: 40.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Fashionable Sunglasses",
    amount: 75.0,
    discount: 15.0,
    rating: 4.6,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Chic Handbag",
    amount: 150.0,
    discount: 30.0,
    rating: 4.8,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Casual Slip-on Shoes",
    amount: 55.0,
    discount: 11.0,
    rating: 4.4,
    percentage: "20%",
    image: "/frame1.png",
  },
  {
    name: "Designer Watch",
    amount: 300.0,
    discount: 60.0,
    rating: 4.9,
    percentage: "20%",
    image: "/frame2.png",
  },
  {
    name: "Modern Backpack",
    amount: 80.0,
    discount: 16.0,
    rating: 4.5,
    percentage: "20%",
    image: "/frame3.png",
  },
  {
    name: "Elegant Evening Shoes",
    amount: 120.0,
    discount: 16.0,
    rating: 4.5,
    percentage: "20%",
    image: "/frame3.png",
  },
];